  
[module]
[[module.mounts]]
# Workaround for https://github.com/gohugoio/hugo/issues/6945
source = "assets/scss/bootstrap/_vendor"
target = "assets/scss/bootstrap/vendor"


[[module.imports]]
path = "github.com/twbs/bootstrap"
	[[module.imports.mounts]]
	source = "scss"
	target = "assets/scss/bootstrap"
	[[module.imports.mounts]]
	source = "js"
	target = "assets/bootstrap"
	[[module.imports.mounts]]
	source = "js/index.esm.js"
	target = "assets/bootstrap/index.js"

[[module.imports]]
path = "github.com/popperjs/popper-core"
disable = false
	[[module.imports.mounts]]
	source = "lib"
	target = "assets/@popperjs/core/lib"

	[[module.imports.mounts]]
	source = "index.d.ts"
	target = "assets/@popperjs/core/index.ts"
